on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS, Windows, Ubuntu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
      - run: mix deps.get
      - run: mix test
